### ISSUE TITLE
show info window on marker when  scroll PageController

### ISSUE THREAD

**Issue by TaifRaoof** [rajayogan/flutter-googlemapeffects#1]
Hi
how to show info window on marker when page controller scroll or on newCameraPosition ?
i see your video it work correctly but when i copy your code and then run project it  didn't work.
thank you

**Comment by rajayogan** [comment]
You have to remove the marker from the allMarkers list and add it again whenever the user scrolls.. There is no way to tap on a marker programmatically as of now..

(Note - You can also change the color of the added marker.. but there are a lot of things you would need to take care while using this hack and slash technique)
